--建表语句，此仅为参考，开发人员可根据需要自行修改脚本
create table SYSTEMCONFIG (
	ID VARCHAR2(36) primary key,
	LEFTNAME VARCHAR2(5),
	ROOTDEPARTNAME VARCHAR2(50),
	ROOTDEPARTNO VARCHAR2(100)
);

--创建索引
create index SYSTEMCONFIG_LEFTNAME on SYSTEMCONFIG (LEFTNAME);
create index SYSTEMCONFIG_ROOTDEPARTNAME on SYSTEMCONFIG (ROOTDEPARTNAME);
create index SYSTEMCONFIG_ROOTDEPARTNO on SYSTEMCONFIG (ROOTDEPARTNO);

--创建注释
comment on column SYSTEMCONFIG.ID is '主键';
comment on column SYSTEMCONFIG.LEFTNAME is '左侧菜单名称';
comment on column SYSTEMCONFIG.ROOTDEPARTNAME is '根部门名称';
comment on column SYSTEMCONFIG.ROOTDEPARTNO is '根部门编号';
