--建表语句，此仅为参考，开发人员可根据需要自行修改脚本
create table SERVICE_VIEWMESSAGE (
	ID varchar(36) primary key,
	TITLE VARCHAR(300),
	REQREGISTERUSER VARCHAR(200),
	REQCONTENT VARCHAR(1000),
	REQTIME TIMESTAMP,
	ISSHOW VARCHAR(50)
);

--创建索引
create index SERVICE_VIEWMESSAGE_TITLE on SERVICE_VIEWMESSAGE (TITLE);
create index SERVICE_VIEWMESSAGE_REQREGISTERUSER on SERVICE_VIEWMESSAGE (REQREGISTERUSER);
create index SERVICE_VIEWMESSAGE_REQCONTENT on SERVICE_VIEWMESSAGE (REQCONTENT);
create index SERVICE_VIEWMESSAGE_REQTIME on SERVICE_VIEWMESSAGE (REQTIME);
create index SERVICE_VIEWMESSAGE_ISSHOW on SERVICE_VIEWMESSAGE (ISSHOW);

--创建注释
comment on column SERVICE_VIEWMESSAGE.ID is '主键';
comment on column SERVICE_VIEWMESSAGE.TITLE is '话题标题';
comment on column SERVICE_VIEWMESSAGE.REQREGISTERUSER is '用户名';
comment on column SERVICE_VIEWMESSAGE.REQCONTENT is '留言内容';
comment on column SERVICE_VIEWMESSAGE.REQTIME is '留言时间';
comment on column SERVICE_VIEWMESSAGE.ISSHOW is '是否显示';
