--建表语句，此仅为参考，开发人员可根据需要自行修改脚本
create table SERVICE_INTERACTION (
	ID varchar(36) primary key,
	REQREGISTERUSER VARCHAR(200),
	TITLE VARCHAR(300),
	REQCONTENT VARCHAR(1000),
	REQTIME VARCHAR(50),
	ISSHOW VARCHAR(50),
	REPSTATUS VARCHAR(50),
	REPCONTENT VARCHAR(1000),
	REPTIME VARCHAR(50)
);

--创建索引
create index INTERACTION_REQREGISTERUSER on SERVICE_INTERACTION (REQREGISTERUSER);
create index INTERACTION_TITLE on SERVICE_INTERACTION (TITLE);
create index INTERACTION_REQCONTENT on SERVICE_INTERACTION (REQCONTENT);
create index INTERACTION_REQTIME on SERVICE_INTERACTION (REQTIME);
create index INTERACTION_ISSHOW on SERVICE_INTERACTION (ISSHOW);
create index INTERACTION_REPSTATUS on SERVICE_INTERACTION (REPSTATUS);
create index INTERACTION_REPCONTENT on SERVICE_INTERACTION (REPCONTENT);
create index INTERACTION_REPTIME on SERVICE_INTERACTION (REPTIME);

--创建注释
comment on column SERVICE_INTERACTION.ID is '主键';
comment on column SERVICE_INTERACTION.REQREGISTERUSER is '申请人';
comment on column SERVICE_INTERACTION.TITLE is '标题';
comment on column SERVICE_INTERACTION.REQCONTENT is '交流内容';
comment on column SERVICE_INTERACTION.REQTIME is '申请时间';
comment on column SERVICE_INTERACTION.ISSHOW is '是否显示';
comment on column SERVICE_INTERACTION.REPSTATUS is '状态';
comment on column SERVICE_INTERACTION.REPCONTENT is '回复内容';
comment on column SERVICE_INTERACTION.REPTIME is '回复时间';
