--建表语句，此仅为参考，开发人员可根据需要自行修改脚本
create table SERVICE_PREMIERLETTER (
	ID varchar(36) primary key,
	TITLE VARCHAR(300),
	REQCONTENT VARCHAR(1000),
	REQTIME TIMESTAMP,
	REQREGISTERUSER VARCHAR(200),
	REPSTATUS VARCHAR(50),
	REPCONTENT VARCHAR(1000),
	REPTIME VARCHAR(100)
);

--创建索引
create index SERVICE_PREMIERLETTER_TITLE on SERVICE_PREMIERLETTER (TITLE);
create index SERVICE_PREMIERLETTER_REQCONTENT on SERVICE_PREMIERLETTER (REQCONTENT);
create index SERVICE_PREMIERLETTER_REQTIME on SERVICE_PREMIERLETTER (REQTIME);
create index SERVICE_PREMIERLETTER_REQREGISTERUSER on SERVICE_PREMIERLETTER (REQREGISTERUSER);
create index SERVICE_PREMIERLETTER_REPSTATUS on SERVICE_PREMIERLETTER (REPSTATUS);
create index SERVICE_PREMIERLETTER_REPCONTENT on SERVICE_PREMIERLETTER (REPCONTENT);
create index SERVICE_PREMIERLETTER_REPTIME on SERVICE_PREMIERLETTER (REPTIME);

--创建注释
comment on column SERVICE_PREMIERLETTER.ID is '主键';
comment on column SERVICE_PREMIERLETTER.TITLE is '标题';
comment on column SERVICE_PREMIERLETTER.REQCONTENT is '邮件内容';
comment on column SERVICE_PREMIERLETTER.REQTIME is '申请时间';
comment on column SERVICE_PREMIERLETTER.REQREGISTERUSER is '申请人';
comment on column SERVICE_PREMIERLETTER.REPSTATUS is '状态';
comment on column SERVICE_PREMIERLETTER.REPCONTENT is '回复内容';
comment on column SERVICE_PREMIERLETTER.REPTIME is '回复时间';
