--建表语句，此仅为参考，开发人员可根据需要自行修改脚本
create table SYSTEM_REQUESTRECORD (
	ID varchar(36) primary key,
	USERACCOUNT VARCHAR(50),
	USERTYPE VARCHAR(50),
	FORMIP VARCHAR(100),
	REQUESTURI VARCHAR(1000),
	REQTIME TIMESTAMP
);

--创建索引
create index SYSTEM_REQUESTRECORD_USERACCOUNT on SYSTEM_REQUESTRECORD (USERACCOUNT);
create index SYSTEM_REQUESTRECORD_USERTYPE on SYSTEM_REQUESTRECORD (USERTYPE);
create index SYSTEM_REQUESTRECORD_FORMIP on SYSTEM_REQUESTRECORD (FORMIP);
create index SYSTEM_REQUESTRECORD_REQUESTURI on SYSTEM_REQUESTRECORD (REQUESTURI);
create index SYSTEM_REQUESTRECORD_REQTIME on SYSTEM_REQUESTRECORD (REQTIME);

--创建注释
comment on column SYSTEM_REQUESTRECORD.ID is '主键';
comment on column SYSTEM_REQUESTRECORD.USERACCOUNT is '操作帐号';
comment on column SYSTEM_REQUESTRECORD.USERTYPE is '用户类型';
comment on column SYSTEM_REQUESTRECORD.FORMIP is '访问IP';
comment on column SYSTEM_REQUESTRECORD.REQUESTURI is '请求地址';
comment on column SYSTEM_REQUESTRECORD.REQTIME is '请求时间';
