--建表语句，此仅为参考，开发人员可根据需要自行修改脚本
create table ATTACHMENT (
	ID VARCHAR2(36) primary key,
	FILENAME VARCHAR2(100),
	FILEPATH VARCHAR2(500),
	FILESIZE NUMBER,
	FILETYPE VARCHAR2(30),
	UPLOADUSERID VARCHAR2(30),
	UPLOADTIME TIMESTAMP,
	CONTEXTPATH VARCHAR2(50)
);

--创建索引
create index ATTACHMENT_FILENAME on ATTACHMENT (FILENAME);
create index ATTACHMENT_FILEPATH on ATTACHMENT (FILEPATH);
create index ATTACHMENT_FILESIZE on ATTACHMENT (FILESIZE);
create index ATTACHMENT_FILETYPE on ATTACHMENT (FILETYPE);
create index ATTACHMENT_UPLOADUSERID on ATTACHMENT (UPLOADUSERID);
create index ATTACHMENT_UPLOADTIME on ATTACHMENT (UPLOADTIME);
create index ATTACHMENT_CONTEXTPATH on ATTACHMENT (CONTEXTPATH);

--创建注释
comment on column ATTACHMENT.ID is '主键';
comment on column ATTACHMENT.FILENAME is '附件名称';
comment on column ATTACHMENT.FILEPATH is '附件路径';
comment on column ATTACHMENT.FILESIZE is '附件大小';
comment on column ATTACHMENT.FILETYPE is '附件类型';
comment on column ATTACHMENT.UPLOADUSERID is '附件上传人';
comment on column ATTACHMENT.UPLOADTIME is '附件上传时间';
comment on column ATTACHMENT.CONTEXTPATH is '工程上下文根';
