--建表语句，此仅为参考，开发人员可根据需要自行修改脚本
create table SYSTEM_DEPARTMENT (
	ID VARCHAR2(36) primary key,
	DEPARTNAME VARCHAR2(50),
	DEPARTNO VARCHAR2(50),
	PARENTNO VARCHAR2(50),
	DEPARTSORT NUMBER
);

--创建索引
create index SYSTEM_DEPARTMENT_DEPARTNAME on SYSTEM_DEPARTMENT (DEPARTNAME);
create index SYSTEM_DEPARTMENT_DEPARTNO on SYSTEM_DEPARTMENT (DEPARTNO);
create index SYSTEM_DEPARTMENT_PARENTNO on SYSTEM_DEPARTMENT (PARENTNO);
create index SYSTEM_DEPARTMENT_DEPARTSORT on SYSTEM_DEPARTMENT (DEPARTSORT);

--创建注释
comment on column SYSTEM_DEPARTMENT.ID is '主键';
comment on column SYSTEM_DEPARTMENT.DEPARTNAME is '部门名称';
comment on column SYSTEM_DEPARTMENT.DEPARTNO is '部门编号';
comment on column SYSTEM_DEPARTMENT.PARENTNO is '上级部门';
comment on column SYSTEM_DEPARTMENT.DEPARTSORT is '部门顺序';
