--建表语句，此仅为参考，开发人员可根据需要自行修改脚本
create table SYSTEM_REGWEBSERVICE (
	ID VARCHAR2(36) primary key,
	INTERFACENO VARCHAR2(20),
	METHOD VARCHAR2(100),
	CLASSNAME VARCHAR2(200),
	STATUS VARCHAR2(50),
	REMARK VARCHAR2(200)
);

--创建索引
create index SYSTEM_REGWEBSERVICE_INTERFACENO on SYSTEM_REGWEBSERVICE (INTERFACENO);
create index SYSTEM_REGWEBSERVICE_METHOD on SYSTEM_REGWEBSERVICE (METHOD);
create index SYSTEM_REGWEBSERVICE_CLASSNAME on SYSTEM_REGWEBSERVICE (CLASSNAME);
create index SYSTEM_REGWEBSERVICE_STATUS on SYSTEM_REGWEBSERVICE (STATUS);
create index SYSTEM_REGWEBSERVICE_REMARK on SYSTEM_REGWEBSERVICE (REMARK);

--创建注释
comment on column SYSTEM_REGWEBSERVICE.ID is '主键';
comment on column SYSTEM_REGWEBSERVICE.INTERFACENO is '接口编号';
comment on column SYSTEM_REGWEBSERVICE.METHOD is '方法名称';
comment on column SYSTEM_REGWEBSERVICE.CLASSNAME is '类名';
comment on column SYSTEM_REGWEBSERVICE.STATUS is '状态';
comment on column SYSTEM_REGWEBSERVICE.REMARK is '备注';
